[project]
name = "acmopportunities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gaballa", email = "lGaballal@yahoo.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    # v this is most likely outdated v
    "google-generativeai>=0.8.6",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "supabase>=2.31.0",
]

[project.scripts]
acmopportunities = "acmopportunities:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
