name: check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Difflint
        shell: bash
        run: |
          git diff origin/main..HEAD | go run github.com/ethanthatonekid/difflint/cli@v0.0.3 --verbose
          exit_code=$?

          if [[ $exit_code -eq 1 ]]; then
            echo "Difflint failed with exit code 1. Failing the check."
            exit 1
          fi
