name: check

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - uses: actions/checkout@v3
        fetch-depth: 0

      - name: Difflint
        shell: bash
        run: git diff origin/main..HEAD | go run github.com/ethanthatonekid/difflint/cli@v0.0.1 --verbose
